%this script is run after 'generate_meta_files.m'.  It runs the C2 and C3
%segmentation and saves their gifs and output data files.  It takes in the
%_thresh.xlsx to get meta data and also uses the _c1mask.mat mask files
%generated in the previous script.  It skips all files that don't have a
%mask.  It is calbirated for 8 bit data

%% Path setup - adds ../functions and ../thirdparty to MATLAB path
scriptDir = fileparts(mfilename('fullpath'));
addpath(fullfile(scriptDir,'..','functions'));
addpath(genpath(fullfile(scriptDir,'..','thirdparty')));

%% Data folder
dataDir = fullfile(scriptDir,'..','data');
cd(dataDir);

%% user input
tableName='Oocyte_sample_list_thresh';
%% gaussian filter settings (keep same as master function)
x1=24;
y1=24;
z1=3;

x2=24;
y2=24;
z2=3;

x3=14;
y3=14;
z3=3;
tShoot=0;
%% x y z pixel size microns (user can change)
xsize=0.3321;
ysize=0.3321;
zsize=2.6;
zRatio=zsize/xsize;

%% display option
% 1 is yes, 0 is no
individOocyteOutlines=1; %display the segmented oocyte stack
tShoot=0; %extra images for troubleshooting segmentation
saveGraphs=1; %save the histgrams to file


%% get thresholds for C2 and c3
metaAll=readtable([tableName '.xlsx']);
metaOutCat=metaAll;  %will hold new meta data generated by C2 C3 thresh function
blankAddT=table(zeros(size(metaAll,1),1),zeros(size(metaAll,1),1),zeros(size(metaAll,1),1),zeros(size(metaAll,1),1),zeros(size(metaAll,1),1),zeros(size(metaAll,1),1),zeros(size(metaAll,1),1),'VariableNames', {'Volume_C1','Volume_C2','Volume_C3','Mean_Int_C2','Mean_Int_C3', 'C2_Thresh', 'C3_Thresh'});
metaOutCat=[metaOutCat,blankAddT];  %initilize columns for new variables;

metaAllPrune=metaAll(metaAll.good_C1_ID==1,:);

uniqueDates=unique(metaAllPrune.date);
for i=1:numel(uniqueDates)  %median plus 3*std of entire day all conditions
    thresh_C2(i)=median(table2array(metaAllPrune(metaAllPrune.date==uniqueDates(i),11)))+3*median(table2array(metaAllPrune(metaAllPrune.date==uniqueDates(i),15)));
    thresh_C3(i)=median(table2array(metaAllPrune(metaAllPrune.date==uniqueDates(i),12)))+3*median(table2array(metaAllPrune(metaAllPrune.date==uniqueDates(i),16)));
end


%% determine directory data
dirList=dir;
names_cell = {dirList.name};
tableFinal=[];

%% for each unique date find a thresh
allUni=unique(metaAll.date);
for i=1:numel(allUni)
    curDate=allUni(i);
    dateIdx=metaAll.date==curDate; %index of rows in this set
    
    curTable=metaAll(dateIdx,:);
    
    for u=1:numel(curTable.name) %loops through all names from the current date and generates a variables which will be added to the current table
        %clear old variables
        clear imstksm segstack minRadBW_CH_Tot
        skipPhase2=0;
        
        if any(strcmp(names_cell,[curTable.name{u} '_c1mask.mat']))  %checks if a .mat c1 binary 3d mask exists for this files        
            %import
            for o=1:3
                [segstack(:,:,:,o)]=importstackone(curTable.name{u}, 3, o); %imports current oocyte
            end
            %smooth
            [imstksm(:,:,:,1)]=smooth3D(segstack(:,:,:,1), x1, y1, z1);  %Apply Gaussian Filter c1
            [imstksm(:,:,:,2)]=smooth3D(segstack(:,:,:,2), x2, y2, z2);  %Apply Gaussian Filter c2
            [imstksm(:,:,:,3)]=smooth3D(segstack(:,:,:,3), x3, y3, z3);  %Apply Gaussian Filter c3

            % import C1 mask
            load([curTable.name{u} '_c1mask.mat'])
            disp([curTable.name{u} ' Oocyte ID Load Complete'])
        else
            skipPhase2=1;   %sets to skip phase 2
            disp([curTable.name{u} ' Oocyte ID Abort'])
        end

        %% run IDobjectanglesV2 and save output
        if skipPhase2==0 
            try
                [metaCur, elePercC2,elePercC3,H1counts,H1countsC2,Cencounts,BWc2sm,BWc3sm]=IDobjectAnglesV3(minRadBW_CH_Tot,imstksm(:,:,:,2),imstksm(:,:,:,3),xsize,ysize,zsize,curTable.name{u},saveGraphs,thresh_C2(i),thresh_C3(i));
                save([curTable.name{u} '_out.mat'],'metaCur', 'elePercC2','elePercC3','H1counts','H1countsC2','Cencounts','BWc2sm','BWc3sm','minRadBW_CH_Tot')
                disp([curTable.name{u} ' complete'])
                %add metaCur o table
                metaCurT=table(metaCur(1),metaCur(2),metaCur(3),metaCur(4),metaCur(5),metaCur(6),metaCur(7),'VariableNames' ,{'Volume_C1','Volume_C2','Volume_C3','Mean_Int_C2','Mean_Int_C3', 'C2_Thresh', 'C3_Thresh'});
                metaOutCat(string(metaAll.name)==curTable.name{u},:)=[metaAll(string(metaAll.name)==curTable.name{u},:),metaCurT];
            catch
                disp([curTable.name{u} ' Aborted Phase 2'])
            end
        end
        close all
    end

end
writetable(metaOutCat,[tableName '2.xlsx'])
